### ISSUE TITLE
hsinspect requirements

### ISSUE THREAD

**Issue by tseenshe** [haskell/hie-bios#13]
Hello!

I encountered the kinds of problems that `hie-bios` is trying to solve when writing https://gitlab.com/tseenshe/hsinspect I hope you don't mind me creating a thread here for discussion (this is not a feature request or bug report as such).

I have created a thread over at https://github.com/DanielG/cabal-helper/issues/75 and it sounds like `cabal-helper` is evolving into something that will solve my problems.

I would like to understand more about `hie-bios` and where it fits in relative to the linked thread. It sounds like `hie-bios` and `cabal-helper` are overlapping: do you have any thoughts on that?

**Comment by fendor** [comment]
Outdated, feel free to reopen if you want to continue this issue
