### ISSUE TITLE
Be able to use several Stack projects (and maybe Cabal too?)

### ISSUE THREAD

**Issue by sir4ur0n** [haskell/hie-bios#191]
Hello,

Currently `hie-bios` supports multiple components for a Stack project, but apparently not multiple Stack projects.

Original issue: https://github.com/haskell/haskell-language-server/issues/145

In `haskell-language-server` we have the following structure (simplified):
```
haskell-language-server/
|- install/
  |- stack.yaml
|- stack.yaml
|- hie.yaml
```

We would like in `hie.yaml` to describe components coming from both Stack projects:
* `./` using `./stack.yaml`
* `./install` using `./install/stack.yaml`

Is such a scenario **currently** possible? If yes, how?

If not: do you think it would make sense for `hie-bios` to support this?

Note: I am more familiar with Stack so I explained the Stack scenario, but apparently the limitations are the same for Cabal, so... Same questions for Cabal 😄 

Thank you!

**Comment by mpickering** [comment]
You can place a `hie.yaml` at the root of each of the projects and `ghcide` and `hie` will work.

**Comment by Sir4ur0n** [comment]
Thank you @mpickering!

I can't find this feature in the README, what do you think about adding it? It seems like a pretty damn useful feature to me 😄

**Comment by fendor** [comment]
The documentation covers this now, afacit
