### ISSUE TITLE
Add `project-file` config option to cabal cradle

### ISSUE THREAD

**Issue by jneira** [haskell/hie-bios#263]
* Like we added `stack-yaml` for the stack cradle
* It could be used to workaround for #195 (and other issues?)
* And the api would be symmetric between both tools

**Comment by fendor** [comment]
I don't think it would help with #195, because cabal uses the same dist-newstyle directory, afaict.

**Comment by jneira** [comment]
Oh, you are right: https://cabal.readthedocs.io/en/latest/cabal-project.html#cmdoption-builddir
So to workaround that we should add a `builddir`option, for both stack and cabal and use it when executing them.

**Comment by fendor** [comment]
Adding a `builddir` option feels like a temporary hack for something that should be fixed eventually by asking for the relevant information directly. I want to avoid adding fields that should become obsolete at some point in the future.

**Comment by jneira** [comment]
So `cabal-build-info` will not generate any build products that may be in another location? is it a pure query of a preexisting build, without trigger any cabal command?

**Comment by fendor** [comment]
It triggers a configure, and builds dependencies if necessary, iirc. It is not a pure query.
