### ISSUE TITLE
Proposal: faster Bios protocol

### ISSUE THREAD

**Issue by pepeiborra** [haskell/hie-bios#270]
Currently the Bios protocol can involve two process calls: one asking for the flags/targets and another asking for the deps. This split means that the Bios program may need to implement some stateful caching in order to respond efficiently to the second request. 

The proposal is to merge both calls into a single one using two env vars: `HIE_BIOS_FLAGS` and `HIE_BIOS_DEPS`. I would add a third output value, the path to ghc, in an env var `HIE_BIOS_GHC_PATH`.

**Comment by wz1000** [comment]
`HIE_BIOS_GHC_PATH` will also unblock #265

**Comment by pepeiborra** [comment]
Is anyone working on `HIE_BIOS_GHC_PATH`? It's the only piece missing and I might find some time to work on it during the incoming days.

**Comment by fendor** [comment]
I am not working on it right now.

**Comment by fendor** [comment]
The first part of this proposal has been implemented, closing it in favour of #401
