### ISSUE TITLE
Cabal cradle doesn't recognize foreign-library sections

### ISSUE THREAD

**Issue by cdsmith** [haskell/hie-bios#341]
I was attempting to follow the tutorial at https://nokomprendo.gitlab.io/posts/tuto_075/2021-09-12-fr-README.html

HLS is flagging the Binding module with `Multi Cradle: no prefixes matched`.  The module is listed in the `other-modules` section of a `foreign-library` section in the cabal file, as follows:

```
foreign-library fibohs
    type:               native-shared
    cc-options:         -std=c++17
    c-sources:          cbits/binding.cpp
    install-includes:   cbits/binding.hpp
    hs-source-dirs:     ffi
    build-depends:      ffi, base
    other-modules:      Binding
```

**Comment by fendor** [comment]
Does it work if you have a `hie.yaml` with 
```yaml
cradle:
  cabal:
```

in the root of your project?

**Comment by cdsmith** [comment]
Yes, it does work in that case!

**Comment by fendor** [comment]
Then that's purely a bug in https://github.com/Avi-D-coder/implicit-hie which is used by HLS when you don't have a `hie.yaml`

**Comment by hasufell** [comment]
> Then that's a bug in https://github.com/Avi-D-coder/implicit-hie which is used by HLS when you don't have a `hie.yaml`

I'm creating the above minimal cradle for every new project, because `implicit-hie` has never worked for me.

**Comment by fendor** [comment]
Yeah, it is right in the most trivial cases, but unfortunately, not even in this repo it works for the tests.
This PR https://github.com/haskell/haskell-language-server/pull/2342 defaults to the equivalent of `cradle: {cabal: }`, but it was never finished.

**Comment by cdsmith** [comment]
Filed https://github.com/Avi-D-coder/implicit-hie/issues/44 over there.  I'll close this now.
