### ISSUE TITLE
gen-hie is producing cabal instead of stack

### ISSUE THREAD

**Issue by PaulJohnson** [haskell/hie-bios#343]
I've got a project with a `stack.yaml` file, but `gen-hie` starts with

    cradle:
      cabal:

**Comment by Ailrun** [comment]
I think you meant to post an issue for https://github.com/Avi-D-coder/implicit-hie. Do you have `dist-newstyle` in your directory? If so, it will use `cabal`; see https://github.com/Avi-D-coder/implicit-hie/blob/master/app/Main.hs#L36-L43

**Comment by PaulJohnson** [comment]
Right, that explains it. I thought `gen-hie` must be using `hie-bios`. And you are correct, I did have `dist-newstyle`. Sorry for the confusion.
