### ISSUE TITLE
Error building stack projet in vs code

### ISSUE THREAD

**Issue by houdelou** [haskell/hie-bios#371]
Hi, it seems the language server is unable to build the project. I suspect it is a permission issue. I had permissions issue in the past in the appdata folder. Is there any way I could change the outputdir and -o to another directory ?

Here is the error I get in vs code :
readCreateProcess: stack "exec" "ghc" "--" "-rtsopts=ignore" "-outputdir" "C:\\Users\\houde\\AppData\\Local\\Temp\\hie-bios-8f902f3286e2fa30" "-o" "C:\\Users\\houde\\AppData\\Local\\hie-bios\\wrapper-340ffcbd9b6dc8c3bed91eb5c533e4e3.exe" "C:\\Users\\houde\\AppData\\Local\\hie-bios\\wrapper-340ffcbd9b6dc8c3bed91eb5c533e4e3.hs" (exit 1): failed

VS Code 1.71.2
Windows 10
Stack 2.7.5

Thanks

**Comment by fendor** [comment]
Hi, thank you for your bug report!

You can overwrite the directory of `-o` via the env variable `HIE_BIOS_CACHE_DIR`. Is the directory in `-outputdir` also problematic? We don't currently have a built-in way to overwrite that, it uses the system `TMP` directory, you can overwrite that for HLS.

**Comment by houdelou** [comment]
Thanks, I see the -o has changed accordingly. I still get the same error though. Maybe this is more of a PC problem if no one has ever had this problem except me.

**Comment by houdelou** [comment]
I also saw this error in the output window :

C:\sr\appdata\wrapper-340ffcbd9b6dc8c3bed91eb5c533e4e3.hs:1:8: error:
    Bad interface file: C:\ghcup\ghc\9.0.2\lib\x86_64-windows-ghc-9.0.2\base-4.15.1.0\Prelude.hi
        magic number mismatch: old/corrupt interface file? (wanted 33214052, got 1)

**Comment by fendor** [comment]
Huh, that's not great. @hasufell is ghc 9.0 broken on windows or something?

**Comment by hasufell** [comment]
Maybe corrupted file. Windows is a disaster wrt file locking, antivirus etc

**Comment by fendor** [comment]
So, best is to re-install? `ghcup rm ghc 9.0.2` followed by `ghcup install ghc 9.0.2`

**Comment by fendor** [comment]
Then I'll close this issue for now, feel free to reopen
