### ISSUE TITLE
"Failed to parse result of calling stack" when sha256 is used in extra-deps

### ISSUE THREAD

**Issue by greenrd** [haskell/hie-bios#377]
I experienced the following error in vscode:

`Failed to parse result of calling stack
/home/user/git/fdd/filepath-1.4.100.0@sha256:45a49fc8c379b33fdba3c8cc96dcf22b15c50995d0f4b8638e9b6b9423d1b877,5875: getDirectoryContents:openDirStream: does not exist (No such file or directory)
`

**Comment by fendor** [comment]
Hello!

Is that reproducible via `stack repl`?

**Comment by greenrd** [comment]
No - actually, now it's not reproducible in vscode either. I guess it parsed the file when I had a syntax error, because I had autosave turned on.
