### ISSUE TITLE
Erroneous detection of Stack projects

### ISSUE THREAD

**Issue by chris-martin** [haskell/hie-bios#386]
Apologies as usual if this is an outdated issue or the wrong project; I'm encountering this problem via several levels of indirection (vscode haskell plugin, haskell-language-server, ...) and so I do not know exactly the infrastructure or how to detect what relevant versions of things are. I recently upgraded to NixOS 22.11 and have experienced this regression.

I have had to go back to placing this `hie.yaml` file in all of my repositories:

```yaml
cradle:
  cabal:
```

My projects all have a `cabal.project` file, and none of them has a `stack.yaml` file. But the IDE has regressed to perpetually trying to use Stack, which I don't even have installed, unless this `hie.yaml` is present.

**Comment by fendor** [comment]
This is most likely caused by implicit-hie which is an additional indirection for cradle detection.

hie-bios in HLS performs no auto-detection at all.

**Comment by hasufell** [comment]
My investigation shows that 1.8.0.0 was using implicit-hie 0.1.2.7 most likely. 1.9.0.0 was using 0.1.4.0 most likely.

The only code difference seems to be these two:

- https://github.com/Avi-D-coder/implicit-hie/commit/4a0da1c2a4d928331d758c5aa91c3097c692c9f3
- https://github.com/Avi-D-coder/implicit-hie/commit/25cf51837afad383f0250518b183b2276e334291

**Comment by hasufell** [comment]
@pepeiborra

**Comment by fendor** [comment]
According to @Avi-D-coder, 0.1.2.7 and 0.1.4.0 are the same version, so it might be a longer standing issue even.

**Comment by hasufell** [comment]
@chris-martin can you share your exact project or at least the whole file-tree?

**Comment by chris-martin** [comment]
Here is one example project:

https://github.com/typeclasses/ascii-char/commit/f6e082f7280795cfb88ec8316880e89d2e45b993

1. ```
   fish> cd (mktemp -d)
   fish> git clone https://github.com/typeclasses/ascii-char.git
   fish> code ascii-char
   ```

2. Open `ascii-char/library/ASCII/Char.hs`

3. VSCode launches and displays a popup that says:
   > Failed to find executable "stack" in $PATH for this Stack project.

**Comment by fendor** [comment]
> Perhaps haskell-language-server ought to be printing version numbers for more of its dependencies. 

Hard agree on that

**Comment by fendor** [comment]
Is this still relevant or did a subsequent release fix this?

**Comment by chris-martin** [comment]
I haven't seen the issue in a while, will reopen if it recurs.
