### ISSUE TITLE
Remove ndmitchell as a contributor

### ISSUE THREAD

**Issue by ndmitchell** [haskell/hie-bios#48]
I'm very happy to contribute as an outside individual who raises PR's, and plan to continue to do so just as much before. However, my experience is that when I have permission to do more (edit master, push to branches etc) my lack of git experience trips me up and I tend to screw everything up. Just removing my contributor status in the Settings tab in github is probably the smart move.

**Comment by ndmitchell** [comment]
Seems I can still edit master. Which isn't good!

**Comment by fendor** [comment]
Hehe, only @mpickering can remove you

**Comment by ndmitchell** [comment]
Is @mpickering still the only person who can do that? If so, perhaps someone else should be granted permissions? (I just want to make a pull request - and through a stroke of luck I didn't actually just commit it to master...)

**Comment by fendor** [comment]
Yeah, I think so, I have no settings tab in the repository.

**Comment by ndmitchell** [comment]
Is it worth considering moving this to the haskell project, given the team working on it is very much subsets of the IDE squad?

**Comment by jneira** [comment]
We are already in the haskell or and @ndmitchell dont have any special rol in the project. However we miss you a lot so the door will we always open 😉

**Comment by ndmitchell** [comment]
I'll never be too far away, and can always raise a PR :)

**Comment by jneira** [comment]
> We are already in the haskell org and @ndmitchell doesnt have any special rol in the project. However we miss you a lot so the door will we always open wink

Well that is not totally true, @ndmitchell is in the haskell ide team: https://github.com/orgs/haskell/teams/haskell-ide
That team has maintainer perms in turn. Let me know if you want to change something about that

**Comment by ndmitchell** [comment]
Happy with that as it stands - it's mostly pushing to master which is something I do by accident fairly regularly :)

**Comment by jneira** [comment]
fortunately master is protected from direct pushes now, it only can be changed via merging an approved pr
